Expand introduction and add contact information
alphagov/govuk-account-team-manual pull request #12
Opened 2021-01-12 14:46 UTC by jonathanglassman

Expand introduction and add contact information.

Trello card: https://trello.com/c/zcQFxzkN/536-increase-tech-docs-and-team-manual-findability

2021-01-12 18:03 UTC, huwd commented on source/index.html.md.erb
> +[Contact the GOV.UK Account team](https://www.account.publishing.service.gov.uk/feedback?_ga=2.207991701.60345245.1610378262-320443275.1592993989&_gac=1.69290274.1610378262.COuKzsGWlO4CFRMfGwodMBwNQQ
Might want to lose the GA param from this.

2021-01-12 18:04 UTC, huwd requested changes

2021-01-12 18:04 UTC, huwd commented on source/index.html.md.erb
> +[Contact the GOV.UK Account team](https://www.account.publishing.service.gov.uk/feedback?_ga=2.207991701.60345245.1610378262-320443275.1592993989&_gac=1.69290274.1610378262.COuKzsGWlO4CFRMfGwodMBwNQQ
```suggestion
[Contact the GOV.UK Account team](https://www.account.publishing.service.gov.uk/feedback) if you have any questions or feedback.
```

2021-01-14 09:26 UTC, jonathanglassman commented
@huwd changes made and commits squashed, please review when you have time and approve hopefully

2021-01-14 10:45 UTC, huwd approved these changes

2021-01-14 10:49 UTC, merged